train:
  batch_size: 4
  num_workers: 10
  learning_rate: 5e-5
  weight_decay: 0.01
  grad_accum_steps: 1
  device: "cpu"
  mixed_precision: True
  save_every_n_steps: 500
  max_grad_norm: 1.0

model:
  hidden_dim: 768
  num_fusion_layers: 2

data:
  audio_sample_rate: 16000
  n_mels: 80
  image_size: 224
  max_text_len: 128